# Generated by Django 3.2.12 on 2025-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='image/', verbose_name='画像')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('description', models.TextField(verbose_name='説明')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品一覧',
            },
        ),
    ]
