# Generated by Django 3.2.12 on 2025-03-30 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('payment_way', models.IntegerField(choices=[('代金引換', 'Cash On Delivery'), ('銀行振込', 'Bank Transfer'), ('クレジットカード', 'Credit Card')], default='代金引換', verbose_name='支払方法')),
                ('status', models.IntegerField(choices=[(0, '未出荷'), (1, '出荷済み'), (2, '取引完了')], default=0, verbose_name='出荷・取引完了情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '注文状況',
                'verbose_name_plural': '注文',
            },
        ),
    ]
