# Generated by Django 3.2.12 on 2025-03-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('代金引換', '代金引換'), ('銀行振込', '銀行振込'), ('クレジットカード', 'クレジットカード')], default='代金引換', max_length=8, verbose_name='支払方法'),
        ),
    ]
