# Generated by Django 3.2.12 on 2025-03-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'カート', 'verbose_name_plural': 'カート'},
        ),
    ]
