# Generated by Django 3.2.12 on 2025-03-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options'),
        ('cart', '0003_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'カート(単品)', 'verbose_name_plural': 'カート(単品)'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.product', verbose_name='商品'),
        ),
        migrations.CreateModel(
            name='CartAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_all', to='cart.cart', verbose_name='カート')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_all_items', to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'カート(ユーザー単位)',
                'verbose_name_plural': 'カート(ユーザー単位)',
            },
        ),
    ]
